### PR TITLE
Add rawtodigi implementation using the Cupla backend

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
Using CUDA as the cupla backend, I see the same performance as with native CUDA.

Using serial operations as the cupla backend is slower than the naive and CUDA implementations; however it was not optimised, and I am not sure what `CUPLA_KERNEL_OPTI` is actually doing (vs. the simpler `CUPLA_KERNEL` call).

**Comment by makortel** [comment]
Thanks, looks good. Before merging I'd like to ask for clarification

This PR fully includes #1, right?

For the the Cupla CPU backend, the input data "transfers" `input` -> `input_h` -> `input_d` are redundant, right?

I found it interesting to see that exactly the same code works fine also in the `main.cc` side, and the backend is fully controlled with the `ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLED` vs. `ALPAKA_ACC_GPU_CUDA_ENABLED`. I suppose for CMSSW purposes we'd need to compile and link both versions.

**Comment by fwyzard** [comment]
> This PR fully includes #1, right?

Yes.

> For the the Cupla CPU backend, the input data "transfers" input -> input_h -> input_d are redundant, right?

Yes, and I think this is one main limitation of Cupla: to keep the code unchanged, it has to introduce these extra operations.   
If we were to use Alpaka directly, it would be up to us to make sure the data are in the correct memory - more work at coding time, potentially less work at runtime, 

> I suppose for CMSSW purposes we'd need to compile and link both versions.

That is the other problem I am thinking about: both libraries export the **same** symbols - `cuplaMemcpy`, `cuplaMemcpyAsync`, *etc.*, so we cannot just link them both to the same plugin.
I am not sure what happens if we try to link two different backend libraries to two different plugins, but I suspect we could quickly end up with linker and/or runtime issues.

**Comment by fwyzard** [comment]
One option could be to put all those symbols in different a namespace for each backend, and rely on the macro definition to pick the right one.

An other option could be to link the cupla backend statically into each plugin.
In fact, cupla itself does this, when one builds with CMake as advertised in the instructions.

**Comment by fwyzard** [comment]
Anyway, I am going to try the other backends and check their performance, as well.

**Comment by makortel** [comment]
Thanks, merging.

**Pull request merged**
