### PR TITLE
Print warnings in yellow rather than red

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
@makortel @waredjeb could you check if this works on your systems ?

**Comment by makortel** [comment]
Works for me.

**Comment by waredjeb** [comment]
> @makortel @waredjeb could you check if this works on your systems ?

Works for me too!

**Comment by fwyzard** [comment]
Thanks.
@makortel , feel free to merge  it fi you like the yellow messages better than the red ones :-)

**Pull request merged**
