### PR TITLE
Move the number of loops to a separate file

### PR DESCRIPTION
**Pull request by fwyzard**
Move the definition of the number of loops to a separate file, to simplify making consistent changes to it for all back ends

### CODE REVIEW

**Comment by fwyzard** [comment]
Currently, this PR includes #37 to avoid conflicts due to file renaming.
I can rebase it once that is merged.

**Comment by makortel** [comment]
Should the following targets also grow dependence on `loops.h`?
```
test-naive: main_naive.cc rawtodigi_naive.h analyzer_naive.cc analyzer_naive.h modules.h
debug-naive: main_naive.cc rawtodigi_naive.h analyzer_naive.cc analyzer_naive.h modules.h
$(BUILD)/analyzer_cuda.o: analyzer_cuda.cc | $(BUILD)
debug-cuda: main_cuda.cc rawtodigi_cuda.cu rawtodigi_cuda.h
test-sycl-opencl: main_sycl.cc analyzer_sycl.cc analyzer_sycl.h rawtodigi_sycl.cc rawtodigi_sycl.hdebug-sycl-opencl: main_sycl.cc analyzer_sycl.cc analyzer_sycl.h rawtodigi_sycl.cc rawtodigi_sycl.h
test-sycl-cuda: main_sycl.cc analyzer_sycl.cc analyzer_sycl.h rawtodigi_sycl.cc rawtodigi_sycl.h
debug-sycl-cuda: main_sycl.cc analyzer_sycl.cc analyzer_sycl.h rawtodigi_sycl.cc rawtodigi_sycl.h
test-sycl: main_sycl.cc analyzer_sycl.cc analyzer_sycl.h rawtodigi_sycl.cc rawtodigi_sycl.h
debug-sycl: main_sycl.cc analyzer_sycl.cc analyzer_sycl.h rawtodigi_sycl.cc rawtodigi_sycl.h
```

**Comment by fwyzard** [comment]
Probably, but I think they already miss many other dependencies.

Rather than fixing them all by hand, I was thinking to autogenerate the dependencies (in a future PR).

**Comment by makortel** [comment]
> Probably, but I think they already miss many other dependencies.

They very likely miss indeed.

> Rather than fixing them all by hand, I was thinking to autogenerate the dependencies (in a future PR).

Yeah, I initially thought the dependencies would stay simple-enough to not autogenerate the dependencies, but then things evolved.

Anyway, I don't feel strongly (because their dependencies are borken already), so I think this is fine after #37 gets in.

**Comment by makortel** [comment]
Sorry, this fell below the radar.

**Pull request merged**
